# Generated by Django 3.2.3 on 2021-05-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_rename_file_data1_post_file_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('training_data', models.FileField(upload_to='post_data')),
                ('test_data', models.FileField(upload_to='post_data')),
                ('label_file_data', models.FileField(upload_to='post_data')),
            ],
        ),
        migrations.DeleteModel(
            name='Model_Data',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
