# Generated by Django 3.2.3 on 2021-05-31 03:41

import apis.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20210531_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_post',
            name='model_type',
            field=models.CharField(default=datetime.datetime(2021, 5, 31, 3, 41, 33, 782564, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_post',
            name='label_file_data',
            field=models.FileField(upload_to=apis.models.group_based_upload_to),
        ),
        migrations.AlterField(
            model_name='model_post',
            name='test_data',
            field=models.FileField(upload_to=apis.models.group_based_upload_to),
        ),
        migrations.AlterField(
            model_name='model_post',
            name='training_data',
            field=models.FileField(upload_to=apis.models.group_based_upload_to),
        ),
    ]
