# Generated by Django 3.2.3 on 2021-06-03 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_auto_20210531_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_post',
            old_name='model_type',
            new_name='framework_type',
        ),
        migrations.RenameField(
            model_name='model_post',
            old_name='title',
            new_name='model_arch_type',
        ),
        migrations.RemoveField(
            model_name='model_post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='model_post',
            name='model_id',
        ),
        migrations.AddField(
            model_name='model_post',
            name='usecase_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
