# Generated by Django 3.2.3 on 2021-06-06 14:53

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20210603_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tf_Config_File_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_file_data', models.FileField(upload_to=apis.models.group_based_upload_to)),
            ],
        ),
    ]
