# Generated by Django 3.2.3 on 2021-06-09 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_tf_config_file_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tf_config_file_post',
            name='uniqueid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
