# Generated by Django 3.2.3 on 2021-05-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=8, unique=True)),
                ('model_name', models.CharField(default='', max_length=8, unique=True)),
                ('model_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
